### ISSUE TITLE
Suggestion: Instant breaking of deepslate with netherite-diamond pickaxe

### ISSUE THREAD

**Issue by sharko789** [Autovw/AdvancedNetheriteFabric#10]
Have you considered bumping up the tool speed of the different tiers, so that netherite-diamond (with Haste II & Efficiency V) could instantly break blocks with a hardness of 3, such as deepslate?
I feel like the high-end tools (hoe, shovel, pickaxe) don't really have a use case yet, other than the increased durability. 
If I did my calculation [based on the wiki](https://minecraft.fandom.com/wiki/Breaking#Speed) correctly, a tool speed of 39 would be requiered to achieve this. Could you add this to the mod or at least make it a configurable option?

**Comment by Autovw** [comment]
This has been on my to do list since the beginning of the mod. Unfortunately bumping the number to 39 will cause balancing issues with other blocks, but I do still have something else planned that would allow for insta-mining deepslate with Efficiency 5 and Haste 2. Just haven't had the time to work on it yet, but it'll hopefully happen soon.
