### ISSUE TITLE
[Crash] with requiem 

### ISSUE THREAD

**Issue by DanMeadWasTaken** [Autovw/AdvancedNetheriteFabric#14]
Game crashes when I equipped a diamond netherite helm in a creative testing world. 
Continues to crash every time I open the player inventory in that world.
The only mod i could think of that could be causing this would be levelz- as it only started doing this after i applied the mod to the pack

https://mclo.gs/PA9yHCS

#Globox1997/LevelZ#243

**Comment by Autovw** [comment]
This issue is caused by other mods using poorly written mixins to change the loading of armor textures. As of Fabric API ``0.62.0`` (and above) this particular Mixin is no longer needed, however some mods still have their Mixin for this, which can lead to this particular issue.

Based on the provided log it's almost impossible to tell which mod is causing this, you'd have to find the mod responsible for [this particular line](https://mclo.gs/PA9yHCS#L1252):
```
at net.minecraft.class_922.redirect$chn000$preventFeatureRendering(class_922.java:1563) ~[client-intermediary.jar:?]
```

There's not much I can do from my end, however I'm gonna leave this issue open for discussion.

**Comment by DanMeadWasTaken** [comment]
So after some testing, it'd seem to actually be caused by requiem- which is also causing a conflict with another mod as is.

I'll go ahead and close the issue on levelz- should've done more testing before making that one, but sometimes after hours of bug testing and talking to various mod developers... your brain kinda just gets mentally drained.

Anyway, I'll go ahead and open a issue on requiem's end and mention this issue in there

**Comment by DanMeadWasTaken** [comment]
just in case there is anything you can do to help me out- or help out requiem team here's all the relevant logs from the latest crash with the combo.

minecraft 1.19.2 quilt
Advanced Netherite (Fabric) 1.6.6
Requiem 2.0.0-beta
[Crash Report](https://mclo.gs/HmBhJAM)
[Log from crash](https://mclo.gs/djrNKTF)
[Latest.log](https://mclo.gs/mg2Pt2o)
