### ISSUE TITLE
Any Config For Fabric

### ISSUE THREAD

**Issue by KevinKharma1** [Autovw/AdvancedNetheriteFabric#6]
Is there a config option when using the fabric version? I have mod menu and other mods have  config option but this mod doesn't. Please reply
Thank you.

**Comment by Autovw** [comment]
The Fabric version does not have a config because Fabric (both Loader and API) doesn't come with such a system by default (unlike Forge). This means I would have to create my own config system and that's something I won't be doing at this point in time. However, as of v1.5.0 you can configure the armor *perks* with a datapack. (see [wiki](https://github.com/Autovw/AdvancedNetheriteFabric/wiki/Configure-armor-perks))
